// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package TokenProvider_mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/n0f4ph4mst3r/TokenCraft/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) GetToken(ctx context.Context, tokenHash string) (models.Token, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 models.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Token, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Token); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(models.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockTokenProvider_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenProvider_Expecter) GetToken(ctx interface{}, tokenHash interface{}) *MockTokenProvider_GetToken_Call {
	return &MockTokenProvider_GetToken_Call{Call: _e.mock.On("GetToken", ctx, tokenHash)}
}

func (_c *MockTokenProvider_GetToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenProvider_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_GetToken_Call) Return(token models.Token, err error) *MockTokenProvider_GetToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenProvider_GetToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (models.Token, error)) *MockTokenProvider_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) RemoveToken(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RemoveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenProvider_RemoveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveToken'
type MockTokenProvider_RemoveToken_Call struct {
	*mock.Call
}

// RemoveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenProvider_Expecter) RemoveToken(ctx interface{}, tokenHash interface{}) *MockTokenProvider_RemoveToken_Call {
	return &MockTokenProvider_RemoveToken_Call{Call: _e.mock.On("RemoveToken", ctx, tokenHash)}
}

func (_c *MockTokenProvider_RemoveToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenProvider_RemoveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_RemoveToken_Call) Return(err error) *MockTokenProvider_RemoveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenProvider_RemoveToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *MockTokenProvider_RemoveToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) SaveToken(ctx context.Context, userID uuid.UUID, appID int64, tokenHash string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, userID, appID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, appID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenProvider_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type MockTokenProvider_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - appID int64
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockTokenProvider_Expecter) SaveToken(ctx interface{}, userID interface{}, appID interface{}, tokenHash interface{}, expiresAt interface{}) *MockTokenProvider_SaveToken_Call {
	return &MockTokenProvider_SaveToken_Call{Call: _e.mock.On("SaveToken", ctx, userID, appID, tokenHash, expiresAt)}
}

func (_c *MockTokenProvider_SaveToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, appID int64, tokenHash string, expiresAt time.Time)) *MockTokenProvider_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokenProvider_SaveToken_Call) Return(err error) *MockTokenProvider_SaveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenProvider_SaveToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, appID int64, tokenHash string, expiresAt time.Time) error) *MockTokenProvider_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}
