// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package AuthService_mocks

import (
	"context"

	"github.com/n0f4ph4mst3r/TokenCraft/internal/grpc/auth"
	"github.com/n0f4ph4mst3r/TokenCraft/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, username string, password string, appID int64) (models.User, auth.TokenPair, error) {
	ret := _mock.Called(ctx, username, password, appID)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 models.User
	var r1 auth.TokenPair
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (models.User, auth.TokenPair, error)); ok {
		return returnFunc(ctx, username, password, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) models.User); ok {
		r0 = returnFunc(ctx, username, password, appID)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) auth.TokenPair); ok {
		r1 = returnFunc(ctx, username, password, appID)
	} else {
		r1 = ret.Get(1).(auth.TokenPair)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int64) error); ok {
		r2 = returnFunc(ctx, username, password, appID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - appID int64
func (_e *MockAuthService_Expecter) Login(ctx interface{}, username interface{}, password interface{}, appID interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, username, password, appID)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, username string, password string, appID int64)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(user models.User, tokenPair auth.TokenPair, err error) *MockAuthService_Login_Call {
	_c.Call.Return(user, tokenPair, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string, appID int64) (models.User, auth.TokenPair, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, token interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, token)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RegisterUser(ctx context.Context, email string, name string, password string) (models.User, error) {
	ret := _mock.Called(ctx, email, name, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (models.User, error)); ok {
		return returnFunc(ctx, email, name, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) models.User); ok {
		r0 = returnFunc(ctx, email, name, password)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, name, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockAuthService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - name string
//   - password string
func (_e *MockAuthService_Expecter) RegisterUser(ctx interface{}, email interface{}, name interface{}, password interface{}) *MockAuthService_RegisterUser_Call {
	return &MockAuthService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, email, name, password)}
}

func (_c *MockAuthService_RegisterUser_Call) Run(run func(ctx context.Context, email string, name string, password string)) *MockAuthService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthService_RegisterUser_Call) Return(user models.User, err error) *MockAuthService_RegisterUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, email string, name string, password string) (models.User, error)) *MockAuthService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RoleCheck provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RoleCheck(ctx context.Context, refreshToken string, role string) (bool, error) {
	ret := _mock.Called(ctx, refreshToken, role)

	if len(ret) == 0 {
		panic("no return value specified for RoleCheck")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, refreshToken, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, refreshToken, role)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, refreshToken, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RoleCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleCheck'
type MockAuthService_RoleCheck_Call struct {
	*mock.Call
}

// RoleCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - role string
func (_e *MockAuthService_Expecter) RoleCheck(ctx interface{}, refreshToken interface{}, role interface{}) *MockAuthService_RoleCheck_Call {
	return &MockAuthService_RoleCheck_Call{Call: _e.mock.On("RoleCheck", ctx, refreshToken, role)}
}

func (_c *MockAuthService_RoleCheck_Call) Run(run func(ctx context.Context, refreshToken string, role string)) *MockAuthService_RoleCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_RoleCheck_Call) Return(b bool, err error) *MockAuthService_RoleCheck_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuthService_RoleCheck_Call) RunAndReturn(run func(ctx context.Context, refreshToken string, role string) (bool, error)) *MockAuthService_RoleCheck_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) UpdateToken(ctx context.Context, refreshToken string) (auth.TokenPair, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateToken")
	}

	var r0 auth.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth.TokenPair, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth.TokenPair); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(auth.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_UpdateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateToken'
type MockAuthService_UpdateToken_Call struct {
	*mock.Call
}

// UpdateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) UpdateToken(ctx interface{}, refreshToken interface{}) *MockAuthService_UpdateToken_Call {
	return &MockAuthService_UpdateToken_Call{Call: _e.mock.On("UpdateToken", ctx, refreshToken)}
}

func (_c *MockAuthService_UpdateToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_UpdateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_UpdateToken_Call) Return(tokenPair auth.TokenPair, err error) *MockAuthService_UpdateToken_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthService_UpdateToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (auth.TokenPair, error)) *MockAuthService_UpdateToken_Call {
	_c.Call.Return(run)
	return _c
}
