// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package TokenSigner_mocks

import (
	"time"

	"github.com/n0f4ph4mst3r/TokenCraft/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenSigner creates a new instance of MockTokenSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenSigner {
	mock := &MockTokenSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenSigner is an autogenerated mock type for the TokenSigner type
type MockTokenSigner struct {
	mock.Mock
}

type MockTokenSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenSigner) EXPECT() *MockTokenSigner_Expecter {
	return &MockTokenSigner_Expecter{mock: &_m.Mock}
}

// SignJWT provides a mock function for the type MockTokenSigner
func (_mock *MockTokenSigner) SignJWT(user models.User, app models.App, ttl time.Duration) (string, error) {
	ret := _mock.Called(user, app, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SignJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.User, models.App, time.Duration) (string, error)); ok {
		return returnFunc(user, app, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(models.User, models.App, time.Duration) string); ok {
		r0 = returnFunc(user, app, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(models.User, models.App, time.Duration) error); ok {
		r1 = returnFunc(user, app, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenSigner_SignJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignJWT'
type MockTokenSigner_SignJWT_Call struct {
	*mock.Call
}

// SignJWT is a helper method to define mock.On call
//   - user models.User
//   - app models.App
//   - ttl time.Duration
func (_e *MockTokenSigner_Expecter) SignJWT(user interface{}, app interface{}, ttl interface{}) *MockTokenSigner_SignJWT_Call {
	return &MockTokenSigner_SignJWT_Call{Call: _e.mock.On("SignJWT", user, app, ttl)}
}

func (_c *MockTokenSigner_SignJWT_Call) Run(run func(user models.User, app models.App, ttl time.Duration)) *MockTokenSigner_SignJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.User
		if args[0] != nil {
			arg0 = args[0].(models.User)
		}
		var arg1 models.App
		if args[1] != nil {
			arg1 = args[1].(models.App)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenSigner_SignJWT_Call) Return(s string, err error) *MockTokenSigner_SignJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenSigner_SignJWT_Call) RunAndReturn(run func(user models.User, app models.App, ttl time.Duration) (string, error)) *MockTokenSigner_SignJWT_Call {
	_c.Call.Return(run)
	return _c
}

// SignOpaque provides a mock function for the type MockTokenSigner
func (_mock *MockTokenSigner) SignOpaque(user models.User, app models.App, secret string) (string, error) {
	ret := _mock.Called(user, app, secret)

	if len(ret) == 0 {
		panic("no return value specified for SignOpaque")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.User, models.App, string) (string, error)); ok {
		return returnFunc(user, app, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(models.User, models.App, string) string); ok {
		r0 = returnFunc(user, app, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(models.User, models.App, string) error); ok {
		r1 = returnFunc(user, app, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenSigner_SignOpaque_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOpaque'
type MockTokenSigner_SignOpaque_Call struct {
	*mock.Call
}

// SignOpaque is a helper method to define mock.On call
//   - user models.User
//   - app models.App
//   - secret string
func (_e *MockTokenSigner_Expecter) SignOpaque(user interface{}, app interface{}, secret interface{}) *MockTokenSigner_SignOpaque_Call {
	return &MockTokenSigner_SignOpaque_Call{Call: _e.mock.On("SignOpaque", user, app, secret)}
}

func (_c *MockTokenSigner_SignOpaque_Call) Run(run func(user models.User, app models.App, secret string)) *MockTokenSigner_SignOpaque_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.User
		if args[0] != nil {
			arg0 = args[0].(models.User)
		}
		var arg1 models.App
		if args[1] != nil {
			arg1 = args[1].(models.App)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenSigner_SignOpaque_Call) Return(s string, err error) *MockTokenSigner_SignOpaque_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenSigner_SignOpaque_Call) RunAndReturn(run func(user models.User, app models.App, secret string) (string, error)) *MockTokenSigner_SignOpaque_Call {
	_c.Call.Return(run)
	return _c
}
