// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package AuthProvider_mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/n0f4ph4mst3r/TokenCraft/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthProvider creates a new instance of MockAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthProvider {
	mock := &MockAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthProvider is an autogenerated mock type for the AuthProvider type
type MockAuthProvider struct {
	mock.Mock
}

type MockAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthProvider) EXPECT() *MockAuthProvider_Expecter {
	return &MockAuthProvider_Expecter{mock: &_m.Mock}
}

// AppById provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) AppById(ctx context.Context, appID int64) (models.App, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for AppById")
	}

	var r0 models.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (models.App, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) models.App); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		r0 = ret.Get(0).(models.App)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_AppById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppById'
type MockAuthProvider_AppById_Call struct {
	*mock.Call
}

// AppById is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
func (_e *MockAuthProvider_Expecter) AppById(ctx interface{}, appID interface{}) *MockAuthProvider_AppById_Call {
	return &MockAuthProvider_AppById_Call{Call: _e.mock.On("AppById", ctx, appID)}
}

func (_c *MockAuthProvider_AppById_Call) Run(run func(ctx context.Context, appID int64)) *MockAuthProvider_AppById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthProvider_AppById_Call) Return(app models.App, err error) *MockAuthProvider_AppById_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockAuthProvider_AppById_Call) RunAndReturn(run func(ctx context.Context, appID int64) (models.App, error)) *MockAuthProvider_AppById_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) GetToken(ctx context.Context, tokenHash string) (models.Token, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 models.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Token, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Token); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(models.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockAuthProvider_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockAuthProvider_Expecter) GetToken(ctx interface{}, tokenHash interface{}) *MockAuthProvider_GetToken_Call {
	return &MockAuthProvider_GetToken_Call{Call: _e.mock.On("GetToken", ctx, tokenHash)}
}

func (_c *MockAuthProvider_GetToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockAuthProvider_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthProvider_GetToken_Call) Return(token models.Token, err error) *MockAuthProvider_GetToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockAuthProvider_GetToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (models.Token, error)) *MockAuthProvider_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) RegisterUser(ctx context.Context, email string, name string, hashPassword []byte) (models.User, error) {
	ret := _mock.Called(ctx, email, name, hashPassword)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) (models.User, error)); ok {
		return returnFunc(ctx, email, name, hashPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) models.User); ok {
		r0 = returnFunc(ctx, email, name, hashPassword)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = returnFunc(ctx, email, name, hashPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockAuthProvider_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - name string
//   - hashPassword []byte
func (_e *MockAuthProvider_Expecter) RegisterUser(ctx interface{}, email interface{}, name interface{}, hashPassword interface{}) *MockAuthProvider_RegisterUser_Call {
	return &MockAuthProvider_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, email, name, hashPassword)}
}

func (_c *MockAuthProvider_RegisterUser_Call) Run(run func(ctx context.Context, email string, name string, hashPassword []byte)) *MockAuthProvider_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthProvider_RegisterUser_Call) Return(user models.User, err error) *MockAuthProvider_RegisterUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthProvider_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, email string, name string, hashPassword []byte) (models.User, error)) *MockAuthProvider_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveToken provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) RemoveToken(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RemoveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthProvider_RemoveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveToken'
type MockAuthProvider_RemoveToken_Call struct {
	*mock.Call
}

// RemoveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockAuthProvider_Expecter) RemoveToken(ctx interface{}, tokenHash interface{}) *MockAuthProvider_RemoveToken_Call {
	return &MockAuthProvider_RemoveToken_Call{Call: _e.mock.On("RemoveToken", ctx, tokenHash)}
}

func (_c *MockAuthProvider_RemoveToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockAuthProvider_RemoveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthProvider_RemoveToken_Call) Return(err error) *MockAuthProvider_RemoveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthProvider_RemoveToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *MockAuthProvider_RemoveToken_Call {
	_c.Call.Return(run)
	return _c
}

// RoleCheck provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) RoleCheck(ctx context.Context, refreshToken string, role string) error {
	ret := _mock.Called(ctx, refreshToken, role)

	if len(ret) == 0 {
		panic("no return value specified for RoleCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, refreshToken, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthProvider_RoleCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleCheck'
type MockAuthProvider_RoleCheck_Call struct {
	*mock.Call
}

// RoleCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - role string
func (_e *MockAuthProvider_Expecter) RoleCheck(ctx interface{}, refreshToken interface{}, role interface{}) *MockAuthProvider_RoleCheck_Call {
	return &MockAuthProvider_RoleCheck_Call{Call: _e.mock.On("RoleCheck", ctx, refreshToken, role)}
}

func (_c *MockAuthProvider_RoleCheck_Call) Run(run func(ctx context.Context, refreshToken string, role string)) *MockAuthProvider_RoleCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthProvider_RoleCheck_Call) Return(err error) *MockAuthProvider_RoleCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthProvider_RoleCheck_Call) RunAndReturn(run func(ctx context.Context, refreshToken string, role string) error) *MockAuthProvider_RoleCheck_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToken provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) SaveToken(ctx context.Context, userID uuid.UUID, appID int64, token string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, userID, appID, token, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, appID, token, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthProvider_SaveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToken'
type MockAuthProvider_SaveToken_Call struct {
	*mock.Call
}

// SaveToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - appID int64
//   - token string
//   - expiresAt time.Time
func (_e *MockAuthProvider_Expecter) SaveToken(ctx interface{}, userID interface{}, appID interface{}, token interface{}, expiresAt interface{}) *MockAuthProvider_SaveToken_Call {
	return &MockAuthProvider_SaveToken_Call{Call: _e.mock.On("SaveToken", ctx, userID, appID, token, expiresAt)}
}

func (_c *MockAuthProvider_SaveToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, appID int64, token string, expiresAt time.Time)) *MockAuthProvider_SaveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthProvider_SaveToken_Call) Return(err error) *MockAuthProvider_SaveToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthProvider_SaveToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, appID int64, token string, expiresAt time.Time) error) *MockAuthProvider_SaveToken_Call {
	_c.Call.Return(run)
	return _c
}

// UserByEmail provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) UserByEmail(ctx context.Context, email string) (models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserByEmail")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_UserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByEmail'
type MockAuthProvider_UserByEmail_Call struct {
	*mock.Call
}

// UserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthProvider_Expecter) UserByEmail(ctx interface{}, email interface{}) *MockAuthProvider_UserByEmail_Call {
	return &MockAuthProvider_UserByEmail_Call{Call: _e.mock.On("UserByEmail", ctx, email)}
}

func (_c *MockAuthProvider_UserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthProvider_UserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthProvider_UserByEmail_Call) Return(user models.User, err error) *MockAuthProvider_UserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthProvider_UserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (models.User, error)) *MockAuthProvider_UserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserById provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) UserById(ctx context.Context, userID uuid.UUID) (models.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserById")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_UserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserById'
type MockAuthProvider_UserById_Call struct {
	*mock.Call
}

// UserById is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthProvider_Expecter) UserById(ctx interface{}, userID interface{}) *MockAuthProvider_UserById_Call {
	return &MockAuthProvider_UserById_Call{Call: _e.mock.On("UserById", ctx, userID)}
}

func (_c *MockAuthProvider_UserById_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthProvider_UserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthProvider_UserById_Call) Return(user models.User, err error) *MockAuthProvider_UserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthProvider_UserById_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (models.User, error)) *MockAuthProvider_UserById_Call {
	_c.Call.Return(run)
	return _c
}
