// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package AppProvider_mocks

import (
	"context"

	"github.com/n0f4ph4mst3r/TokenCraft/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppProvider creates a new instance of MockAppProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppProvider {
	mock := &MockAppProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppProvider is an autogenerated mock type for the AppProvider type
type MockAppProvider struct {
	mock.Mock
}

type MockAppProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppProvider) EXPECT() *MockAppProvider_Expecter {
	return &MockAppProvider_Expecter{mock: &_m.Mock}
}

// AppById provides a mock function for the type MockAppProvider
func (_mock *MockAppProvider) AppById(ctx context.Context, appID int64) (models.App, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for AppById")
	}

	var r0 models.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (models.App, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) models.App); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		r0 = ret.Get(0).(models.App)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppProvider_AppById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppById'
type MockAppProvider_AppById_Call struct {
	*mock.Call
}

// AppById is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
func (_e *MockAppProvider_Expecter) AppById(ctx interface{}, appID interface{}) *MockAppProvider_AppById_Call {
	return &MockAppProvider_AppById_Call{Call: _e.mock.On("AppById", ctx, appID)}
}

func (_c *MockAppProvider_AppById_Call) Run(run func(ctx context.Context, appID int64)) *MockAppProvider_AppById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppProvider_AppById_Call) Return(app models.App, err error) *MockAppProvider_AppById_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockAppProvider_AppById_Call) RunAndReturn(run func(ctx context.Context, appID int64) (models.App, error)) *MockAppProvider_AppById_Call {
	_c.Call.Return(run)
	return _c
}
