// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package UserProvider_mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/n0f4ph4mst3r/TokenCraft/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// RegisterUser provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) RegisterUser(ctx context.Context, email string, name string, password string) (models.User, error) {
	ret := _mock.Called(ctx, email, name, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (models.User, error)); ok {
		return returnFunc(ctx, email, name, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) models.User); ok {
		r0 = returnFunc(ctx, email, name, password)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, name, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserProvider_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - name string
//   - password string
func (_e *MockUserProvider_Expecter) RegisterUser(ctx interface{}, email interface{}, name interface{}, password interface{}) *MockUserProvider_RegisterUser_Call {
	return &MockUserProvider_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, email, name, password)}
}

func (_c *MockUserProvider_RegisterUser_Call) Run(run func(ctx context.Context, email string, name string, password string)) *MockUserProvider_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserProvider_RegisterUser_Call) Return(user models.User, err error) *MockUserProvider_RegisterUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, email string, name string, password string) (models.User, error)) *MockUserProvider_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RoleCheck provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) RoleCheck(ctx context.Context, refreshToken string, role string) error {
	ret := _mock.Called(ctx, refreshToken, role)

	if len(ret) == 0 {
		panic("no return value specified for RoleCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, refreshToken, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserProvider_RoleCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleCheck'
type MockUserProvider_RoleCheck_Call struct {
	*mock.Call
}

// RoleCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - role string
func (_e *MockUserProvider_Expecter) RoleCheck(ctx interface{}, refreshToken interface{}, role interface{}) *MockUserProvider_RoleCheck_Call {
	return &MockUserProvider_RoleCheck_Call{Call: _e.mock.On("RoleCheck", ctx, refreshToken, role)}
}

func (_c *MockUserProvider_RoleCheck_Call) Run(run func(ctx context.Context, refreshToken string, role string)) *MockUserProvider_RoleCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserProvider_RoleCheck_Call) Return(err error) *MockUserProvider_RoleCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserProvider_RoleCheck_Call) RunAndReturn(run func(ctx context.Context, refreshToken string, role string) error) *MockUserProvider_RoleCheck_Call {
	_c.Call.Return(run)
	return _c
}

// UserByEmail provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) UserByEmail(ctx context.Context, email string) (models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserByEmail")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_UserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByEmail'
type MockUserProvider_UserByEmail_Call struct {
	*mock.Call
}

// UserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) UserByEmail(ctx interface{}, email interface{}) *MockUserProvider_UserByEmail_Call {
	return &MockUserProvider_UserByEmail_Call{Call: _e.mock.On("UserByEmail", ctx, email)}
}

func (_c *MockUserProvider_UserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_UserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_UserByEmail_Call) Return(user models.User, err error) *MockUserProvider_UserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_UserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (models.User, error)) *MockUserProvider_UserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserById provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) UserById(ctx context.Context, userID uuid.UUID) (models.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserById")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_UserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserById'
type MockUserProvider_UserById_Call struct {
	*mock.Call
}

// UserById is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserProvider_Expecter) UserById(ctx interface{}, userID interface{}) *MockUserProvider_UserById_Call {
	return &MockUserProvider_UserById_Call{Call: _e.mock.On("UserById", ctx, userID)}
}

func (_c *MockUserProvider_UserById_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserProvider_UserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_UserById_Call) Return(user models.User, err error) *MockUserProvider_UserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_UserById_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (models.User, error)) *MockUserProvider_UserById_Call {
	_c.Call.Return(run)
	return _c
}
