// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package Hasher_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockHasher
func (_mock *MockHasher) Hash(str string) ([]byte, error) {
	ret := _mock.Called(str)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(str)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(str)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(str)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - str string
func (_e *MockHasher_Expecter) Hash(str interface{}) *MockHasher_Hash_Call {
	return &MockHasher_Hash_Call{Call: _e.mock.On("Hash", str)}
}

func (_c *MockHasher_Hash_Call) Run(run func(str string)) *MockHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Hash_Call) Return(bytes []byte, err error) *MockHasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockHasher_Hash_Call) RunAndReturn(run func(str string) ([]byte, error)) *MockHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
