// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package CacheProvider_mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheProvider creates a new instance of MockCacheProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheProvider {
	mock := &MockCacheProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheProvider is an autogenerated mock type for the CacheProvider type
type MockCacheProvider struct {
	mock.Mock
}

type MockCacheProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheProvider) EXPECT() *MockCacheProvider_Expecter {
	return &MockCacheProvider_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) Del(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheProvider_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockCacheProvider_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockCacheProvider_Expecter) Del(ctx interface{}, keys ...interface{}) *MockCacheProvider_Del_Call {
	return &MockCacheProvider_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockCacheProvider_Del_Call) Run(run func(ctx context.Context, keys ...string)) *MockCacheProvider_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCacheProvider_Del_Call) Return(err error) *MockCacheProvider_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheProvider_Del_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockCacheProvider_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) Get(ctx context.Context, key string, dest interface{}) (bool, error) {
	ret := _mock.Called(ctx, key, dest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) (bool, error)); ok {
		return returnFunc(ctx, key, dest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) bool); ok {
		r0 = returnFunc(ctx, key, dest)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = returnFunc(ctx, key, dest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - dest interface{}
func (_e *MockCacheProvider_Expecter) Get(ctx interface{}, key interface{}, dest interface{}) *MockCacheProvider_Get_Call {
	return &MockCacheProvider_Get_Call{Call: _e.mock.On("Get", ctx, key, dest)}
}

func (_c *MockCacheProvider_Get_Call) Run(run func(ctx context.Context, key string, dest interface{})) *MockCacheProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCacheProvider_Get_Call) Return(b bool, err error) *MockCacheProvider_Get_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCacheProvider_Get_Call) RunAndReturn(run func(ctx context.Context, key string, dest interface{}) (bool, error)) *MockCacheProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) Set(ctx context.Context, key string, value interface{}, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheProvider_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheProvider_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - ttl time.Duration
func (_e *MockCacheProvider_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockCacheProvider_Set_Call {
	return &MockCacheProvider_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockCacheProvider_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, ttl time.Duration)) *MockCacheProvider_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCacheProvider_Set_Call) Return(err error) *MockCacheProvider_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheProvider_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value interface{}, ttl time.Duration) error) *MockCacheProvider_Set_Call {
	_c.Call.Return(run)
	return _c
}
